spring:
  application:
    name: spring-ai-mcp

  threads:
    virtual:
      enabled: true
  ai:
#    mcp:
#      client:
#        stdio:
#          enabled: true
#          servers-configuration: classpath:/mcp-servers-config.json
    ollama:
      chat:
        model: llama3.2
      embedding:
        options:
          model: nomic-embed-text
  main:
    banner-mode: off

server:
  port: 8103

api:
  key:
    brave: ${BRAVE_API_KEY}



